language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - oracle-java8-set-default

install:
- pip install youtube-dl
script:
- python test/test_1.py
- python test/youtube_dl_version.py
